[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycelium2 = "CMLBhrxJKPXr8GEJznTvgj9yiEskNH1anA2UUpQ5kV4G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/xeony/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
